<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <PackageId>Covenant</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <ToolCommandName>dotnet-covenant</ToolCommandName>
  </PropertyGroup>

  <PropertyGroup Label="Package Information">
    <Description>A dotnet tool that generate SBOM:s from source code artifacts.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\**" />
    <EmbeddedResource Remove="Features\**" />
    <None Remove="Features\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Reporting\Templates\Template.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Reporting\Templates\Template.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Buildalyzer" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.VisualStudio.SolutionPersistence"/>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NuGet.Packaging" />
    <PackageReference Include="Rosetta" />
    <PackageReference Include="Scriban" />
    <PackageReference Include="Semver" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Analyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Spectre.IO" />
    <PackageReference Include="System.CommandLine" />

    <!-- Override vulnerable versions -->
    <PackageReference Include="Microsoft.Build" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Covenant.Core\Covenant.Core.csproj" />
    <ProjectReference Include="..\Covenant.CycloneDx\Covenant.CycloneDx.csproj" />
    <ProjectReference Include="..\Covenant.Spdx\Covenant.Spdx.csproj" />
  </ItemGroup>

</Project>
